version: '3'
services:
  hk-nginx:
    container_name: hk-nginx-sender
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - network
  
  app:
    container_name: hk-app-sender
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    networks:
      - network
  
networks:
  network:
    external:
      name: my-net

