version: '3'

services:

  hk-mysql:
   container_name: hk-mysql
   volumes:
   - db_data:/var/lib/mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
   networks:
   - network
  
volumes:
  db_data: {}
  
networks:
  network:
    external:
      name: my-net
